# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='no_users',
            field=models.IntegerField(default=0),
        ),
    ]
